[package]
name = "i18n_error_impl"
version = "0.1.0"
edition = "2021"
authors = ["Daisuke Ito <daisuke.ito.cs@gmail.com>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.46", features = ["full"] }
proc-macro2 = "1.0.74"
quote = "1.0.35"
