[package]
name = "i18n_error"
version = "0.1.0"
authors = ["Daisuke Ito <daisuke.ito.cs@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.46", features = ["full"] }
proc-macro2 = "1.0.74"
quote = "1.0.35"
